### ISSUE TITLE
[Wiki improvement] Add a proper warning about cachy repos replacing all packages of an existing arch system

### ISSUE THREAD

**Issue by hazelshantz** [CachyOS/wiki#77]
after going through an extensive research and testing of cachy, I've noticed that adding the repos to an existing arch system wants to replace all the packages of Arch. the wiki has no warning about this, and this may be bad for some users that want to only select packages from cachy repos and keep their existing vanilla arch. 

for other users that indeed want to fully convert to cachy, then let them know the steps with proper warnings. 

Proporsal:

instead of having
![image](https://github.com/user-attachments/assets/4b00ba94-c9b8-4430-a879-040763136c58)

add the warning, and steps for a full cachy conversion, then steps to add cachy repos as optional, while keeping the existing arch installation.

this way you ensure users don't break their systems in the process, as there may be users that may not read and run commands blindly. sometimes you have to add a big warning, that way nobody can blame you.

best regards.

**Comment by 1Naim** [comment]
@Shendisx Do we really need this? I think the steps are pretty explicit already so all responsibility falls to the user if they failed in the middle of adding the repositories somehow. Also I would argue that having select repos added may be worse than having the full suite altogether. 

If a user wants to only have select packages from select repositories, then they have to either:
a). Grab the packages from our mirrors -- this is a manual process as every update is not handled from the package manager so each time there is an update, said user will need to regrab the updated package from the mirror.
b). Build from our PKGBUILD -- this is also a manual process, but it's easier to keep track of updates because git is tracking the updated PKGBUILDs

**Comment by hazelshantz** [comment]
I think it's better to warn than sorry. you don't know what kind of users may use your service/product. 
the closest example of a similar issue was the KDE plasma themes deleting the data of users, which was handled by adding a proper warning so the user is informed about the risks.
regarding the packages, I think I've explained it properly. I hope this gets added to the wiki.

**Comment by ptr1337** [comment]
> I think it's better to warn than sorry. you don't know what kind of users may use your service/product. the closest example of a similar issue was the KDE plasma themes deleting the data of users, which was handled by adding a proper warning so the user is informed about the risks. regarding the packages, I think I've explained it properly. I hope this gets added to the wiki.

The CachyOS packages follow exactly the same PKGBUILD, as archlinux does in 95% of the cases. There is no difference outside of the optimizations.

Pacman can not touch your home, nor delete anything while updating.

**Comment by hazelshantz** [comment]
sure, but a little warning won't hurt. 
best regards.
